### PR TITLE
Linked URL to player profiles in League Leaders

### PR DESCRIPTION
**Pull request by Jwwason**
Linked URL to players perspective profiles in league leaders page

### CODE REVIEW

**Review by roundleague — COMMENTED** [review]
This is great, thank you for this. In your opinion does it look better if we hyper link just the name (like you did here) or hyperlink the whole row, including the "1. FirstName LastName - 33.5"

Can we also make the link text bolder? You can add a class to the "<a>" element and make the class have "font-weight: 600" or "font-weight: bolder" - Sorry I didn't mention this in the ticket, this is an add-on!

Good stuff boiiii

**Comment by Jwwason** [comment]
I think it looks fine as it is because in the franchise page we did the same thing in the "leading scorer" where the name is hyper linked but not the number.

**Comment by Jwwason** [comment]
Isn't the text already bolded? It looks bolded to me, and it already has "font-weight: bold" in the code

**Comment by roundleague** [comment]
> Isn't the text already bolded? It looks bolded to me, and it already has "font-weight: bold" in the code

You are correct, lol good catch

**Pull request merged**
